version: '3'
services:
  app: &app
    build: .
    environment:
      - PYTHONPATH=/usr/src/app
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
    networks:
      - ns

  redis:
    image: redis:5.0.7
    networks:
      - ns

networks:
  ns:
    external:
      name: my-network
