version: '3'
services:
  mako:
    build: .
    environment:
      - PYTHONPATH=/usr/src/app
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis

  redis:
    image: redis:5.0.9
    command: redis-server --appendonly yes
    volumes:
      - ./data:/data
