version: '3'
services:
  mako:
    build: .
    environment:
      - PYTHONPATH=/usr/src/app
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
    networks:
      - ns

  redis:
    image: redis:5.0.9
    command: redis-server --appendonly yes
    volumes:
      - ./data:/data
    networks:
      - ns

networks:
  ns:
    external:
      name: my-network
