token: my-bot-token
logging_level: DEBUG
redis:
  host: redis
  port: 6379
levels:
  1: "Larve stellaire de rampant"
  2: "Cocon stellaire de rampant"
  3: "Rampant"
  4: "Ersatz d'homoncule"
  5: "Homoncule"
  7: "Normie"
  8: "Normie éclairé"
  9: "Normie transcendé"
  10: "Normie ascensionné"
  11: "Weeb refoulé"
  12: "Weeb assumé"
  13: "Weeb éclairé"
  14: "Weeb transcendé"
  15: "Weeb ascensionné"
  16: "Hikikomori suspecté"
  17: "Hikikomori auto-diagnostiqué"
  18: "Hikikomori confirmé"
  19: "Hikikomori transcendé"
  20: "Hikikomori ascensionné"
